version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/schedule_generator
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/schedule_generator
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: schedule_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/pgdata
    ports:
      - "5432:5432"

volumes:
  postgres:
