<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240213150338 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD5FB8D933D1A3E7 ON tournament (tournament_id)');
        $this->addSql('CREATE TABLE tournament_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, tournament_id INT NOT NULL, team1_id INT NOT NULL, team2_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5C4BB35B33D1A3E7 ON tournament_participant (tournament_id)');
        $this->addSql('CREATE INDEX IDX_5C4BB35BE72BCFA4 ON tournament_participant (team1_id)');
        $this->addSql('CREATE INDEX IDX_5C4BB35BF59E604A ON tournament_participant (team2_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D933D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament_participant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35B33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35BE72BCFA4 FOREIGN KEY (team1_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35BF59E604A FOREIGN KEY (team2_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D933D1A3E7');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35B33D1A3E7');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35BE72BCFA4');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35BF59E604A');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_participant');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
